Feature: Book borrowing
  In order to read book that I am interested in
  As a reader
  I need to be able to borrow book from library

  Scenario: Book borrowing
#    Given ...
#    And ...
#    When ...
#    Then ...
#    And ...

#  Scenario: Reader can't borrow same book twice

#  Scenario: Reader can keep maximum 5 books
